### PR TITLE
Add type-checking

### PR DESCRIPTION
**Pull request by antonykamp**
I've added type checking by introducing two variable types. Both come with an initialization button, getter, and setter. I also updated the examples.

### CODE REVIEW

**Review by kohlros — APPROVED** [review]
This works really well. Is it possible to add it to the "crossover"-block and "mutate a random bit in"-block as well ?

**Comment by antonykamp** [comment]
I thought I already added a check for "crossover_strategy" to "crossover":

https://github.com/HPI-ELEA/elea/blob/6dee97b604d0a7134a16edb90b77b5f8a8a2b9ad/static/scripts/newblocks.js#L418

https://github.com/HPI-ELEA/elea/blob/6dee97b604d0a7134a16edb90b77b5f8a8a2b9ad/static/scripts/newblocks.js#L575

or do you mean the block in [ea_blocks.js](https://github.com/HPI-ELEA/elea/blob/add-type-checking/static/scripts/ea_blocks.js)?

And you're right that I missed the output for "ea_mutate" :D

**Comment by kohlros** [comment]
This check in the "crossover"-block works. Is it possible to only allow the crossover of individuals in the remaining variables of this block? Something similar to the way the "get_individual"-block works. However, I am not sure which inputs this function can/should handle.

**Comment by antonykamp** [comment]
It should have already been implemented for example in 

https://github.com/HPI-ELEA/elea/blob/6dee97b604d0a7134a16edb90b77b5f8a8a2b9ad/static/scripts/newblocks.js#L424

or what do you mean with "the remaining variables of this block"?

**Review by kohlros — APPROVED** [review]

**Pull request merged**
