### PR TITLE
One plus lambda example

### PR DESCRIPTION
**Pull request by kohlros**
Built the 1+lambda algo and linked it where necessary.

### CODE REVIEW

**Comment by antonykamp** [comment]
Correct me if I'm wrong: 1+lambda means I use the best individual from the last population to generate a new one. In this case, I'm not sure if `parent_population` is a set because it holds just one individual. Is it necessary because we are using blocks like `Init population with mu individuals with the init strategy xxx` and `merge xxx with xxx`? If so, we could add some blocks for this because I was confused in the first place :D

**Review by antonykamp — COMMENTED** [review]
Correct me if I'm wrong: 1+lambda means I use the best individual from the last population+the parent of the last population to generate a new population.

In this case, I'm not sure if parent_population is a set because it holds just one individual. Is it necessary because we are using blocks like Init population with mu individuals with the init strategy xxx and merge xxx with xxx? If so, we could add some blocks for this because I was confused in the first place :D

**Comment by antonykamp** [comment]
screenshot

I have the feeling, that you generate a new offspring1, add it to offspring_population and delete it by this line. It that possible?

<details><summary>Browser metadata</summary>





```
Path:      /workspace.html?example=onepluslambda
Browser:   Firefox 94.0 on Windows 10
Viewport:  2560 x 1325 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-6--hpi-elea.netlify.app%2Fworkspace.html%3Fexample%3Donepluslambda&os=Windows&os_version=10&browser=Firefox&browser_version=94.0&resolution=2560x1325&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-6--hpi-elea.netlify.app/workspace.html?example=onepluslambda) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=618c262366ad120008f37fda&commentID=618e348187cc5475cae48b9a&resolution=resolved)

**Comment by kohlros** [comment]
As of right now we do not have any blocks, that work on a single individual. Because of this, things such as setting the parent are a bit awkward. We should probably add these blocks in the future.

**Review by antonykamp — COMMENTED** [review]
I like the comments you have added! If `offspring1` is a single individual, please add a comment here, too :D

**Comment by antonykamp** [comment]
#36 merged

**Pull request closed without merging**
