### PR TITLE
Add `wait` block

### PR DESCRIPTION
**Pull request by antonykamp**
I added a wait block to enable users to slow down the execution and better see the development in future blocks. It uses a simple implementation by comparing the difference between starting and the current date with the waiting time. It cannot use async functions because blockly doesn't support it (see https://github.com/google/blockly/issues/2228).

### CODE REVIEW

**Comment by kohlros** [comment]
The toolbox has lost its color. 
In the comment of the code you said you multiply the time by a factor of 10 to translate roughly to seconds (which seems to be a good factor). However this factor is not yet implemented.

**Comment by antonykamp** [comment]
screenshot

> The toolbox has lost its color. 

I don't know what you mean :) The experimental tab was always black.

And I've added a zero to the string-representation of the code here:

https://github.com/HPI-ELEA/elea/blob/9be3e60e45a4de25b5089030b4370b9589c251b1/static/scripts/newblocks.js#L712

Do you think it's better to multiply the variable wait_period by ten instead of adding a zero? 
<details><summary>Browser metadata</summary>





```
Path:      /workspace.html?example=full
Browser:   Firefox 97.0 on Windows 10
Viewport:  1920 x 1085 @1x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-53--hpi-elea.netlify.app%2Fworkspace.html%3Fexample%3Dfull&os=Windows&os_version=10&browser=Firefox&browser_version=97.0&resolution=1920x1085&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-53--hpi-elea.netlify.app/workspace.html?example=full) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=621766d99ec20a000715c082&commentID=6218803b90b159669f8f7a17&resolution=resolved)

**Comment by kohlros** [comment]
I missed the added 0 there. In this case my testing suggests, that we stick to a factor of 1000 (sleep 2000 resulted in a 2 second wait for me). 
As for the color: In this version the left border is cut off in my browser. However I think that this problem is already fixed on the main branch.

**Comment by antonykamp** [comment]
Then I'll update it to a factor of 1000 👍 
As for the color: fixed with #51

**Review by kohlros — APPROVED** [review]

**Pull request merged**
