### PR TITLE
[plotting] add plotting areas to output

### PR DESCRIPTION
**Pull request by kohlros**
This PR is a preparation for the plotting feature(#81) . 

It implements a method that generates a canvas in the output column in which the plots will be drawn. To improve the optics of the layout a border between content in the output column is introduced.

### CODE REVIEW

**Comment by antonykamp** [comment]
Is there a possibility to use the function `addNewOutputEntry` in `addNewPlotEntry`? I tried with #55  to create a universal functionality to add stuff to the output column :)

**Comment by kohlros** [comment]
Of course. I will push the necessary changes to the Plothandler PR (#79). This PR can now be deleted as far as I am concerned.

**Comment by antonykamp** [comment]
That's possible. Do you need the style changes in the css file?

**Comment by kohlros** [comment]
I could put them in the main PR or create an extra PR for it. What do you think ?

**Comment by antonykamp** [comment]
I would put it into #79 :)

**Comment by antonykamp** [comment]
Closed, because we use `addNewOutputEntry` now and don't need `addNewPlotEntry` anymore

**Pull request closed without merging**
