### PR TITLE
Add workspace title

### PR DESCRIPTION
**Pull request by antonykamp**
Adds a workspace title that shows the current workspace name and if the user has unsaved changes.

### CODE REVIEW

**Comment by kohlros** [comment]
The title takes up a bit too much space. This makes the actual workspace smaller and the top of the page looks very crowded this way. 

Small hint: In workspace.js workspaceTile is missing a 't'.

**Comment by antonykamp** [comment]
What do you think about removing "Use blocks from the toolbar on the left to customize your algorithm or drag existing blocks into a new order" and making the title a bit smaller? :D

**Comment by kohlros** [comment]
Putting the workspace title there seems more reasonable. I wouldn't remove it entirely though. Maybe we can but this text under the toolbar or some other empty space.

**Comment by antonykamp** [comment]
screenshot

Do you mean this space?


<details><summary>Browser metadata</summary>





```
Path:      /workspace.html?example=empty
Browser:   Firefox 94.0 on Windows 10
Viewport:  2560 x 1325 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-17--hpi-elea.netlify.app%2Fworkspace.html%3Fexample%3Dempty&os=Windows&os_version=10&browser=Firefox&browser_version=94.0&resolution=2560x1325&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-17--hpi-elea.netlify.app/workspace.html?example=empty) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=61a48ff96f382100080c5a8a&commentID=61a4a64d34467b0a067e7bf2&resolution=resolved)

**Comment by kohlros** [comment]
Yes. Maybe change the text to "Use blocks from this toolbar" in this case or you can find an even better spot, where this fits in.

**Comment by antonykamp** [comment]
Placing the text there would be difficult because the toolbox is rendered by blockly itself.

**Comment by kohlros** [comment]
Maybe we can add the text below the blockly environment or under the button row. If that doesn't work, I think it would be best to just delete the text.

**Pull request merged**
