### PR TITLE
[plotting] improve optics of plots and code 

### PR DESCRIPTION
**Pull request by kohlros**
I made sure the legend on a graph is only one line so that the graph takes up most of the space (lines 93-96). I also ran the prettier formatting comand on it, which I somehow hadn't done before.

### CODE REVIEW

**Comment by antonykamp** [comment]
screenshot

That means, that we allow only seven datasets?


<details><summary>Browser metadata</summary>





```
Path:      /workspace?example=simple
Browser:   Firefox 100.0 on Windows 10
Viewport:  2560 x 1297 @1.5x
Language:  en-US
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-132--hpi-elea.netlify.app%2Fworkspace%3Fexample%3Dsimple&os=Windows&os_version=10&browser=Firefox&browser_version=100.0&resolution=2560x1297&speed=1&start=true&ref=netlify-source)



</details>

[Open Deploy Preview](https://deploy-preview-132--hpi-elea.netlify.app/workspace?example=simple) · [Mark as Resolved](https://app.netlify.com/cdp/resolve?deployID=6297c6215a7a5c000839b054&commentID=629858dea58fcf4d36ff522c&resolution=resolved)

**Comment by kohlros** [comment]
No. It is just the legend only shows 7 of the Dataset-to-color-matchings now. It is still possible to create as many Datasets as you want (and draw them).

**Comment by antonykamp** [comment]
But it's not possible to show more than 7 in the legend, correct?

**Comment by kohlros** [comment]
Correct. I think this is better than having the size of the plot be reduced. I am working on a fullscreen option for graphs, where everything can be shown properly

**Review by antonykamp — APPROVED** [review]

**Pull request merged**
