### PR TITLE
Migrate to bootstrap 5.2 and implement offcanvas

### PR DESCRIPTION
**Pull request by geromequa**
implemented the bootstrap offcanvas on all pages to fix layout issues, when not in a full-screen tab. to do this bootstrap needed to be updated to version 5.2. the first two commits migrate bootstrap to version 5.2 and fix minor issues resulting from the migration. the third commit then implements the offcanvas. additionally the color of the jumbotron on index, legal, documentation and faq pages had to be changed due to the bootstrap update.

ps: accidently created this branch of of add_threadblock_tooltips_and_rework_naming branch. pls only merge this PR after merging PR #167.

### CODE REVIEW

**Comment by kohlros** [comment]
The space between the main navbar (demo,FAQ,documentation,...) and the workspace navbar (containing run,abort, show code,....) is now too large. 
The color change looks cool. We could ask someone if it fits with the overall style.

**Comment by geromequa** [comment]
@kohlros fixed the gap under the navbar and the merge conflict. ready to merge on my end.

**Comment by kohlros** [comment]
Some text elements are now too large: The title in the workspace header and the description of categories in the documentation.

**Comment by geromequa** [comment]
fixed the fontsize bug in documentation. also noticed the white stripe in my browser but i think it looks better this way. looked very crammed before

**Pull request merged**
