### PR TITLE
one,λ example imlpemented

### PR DESCRIPTION
**Pull request by kohlros**
one_λ algorithm works and is linked where necessary. Getting to the new generation could be implemented better, for example by using a custom made block.

### CODE REVIEW

**Review by antonykamp — COMMENTED** [review]
I have the same point as in #6 :D `parent_population` is a set with one individual :/

**Comment by kohlros** [comment]
I couldn't find blocks that operate on a single individual and had to do some work-arounds. We should probably add those blocks in the future.

**Review by antonykamp — COMMENTED** [review]
I like the comments you have added! If `offspring1` is a single individual, please add a comment here, too :D

**Comment by antonykamp** [comment]
Merged #37

**Pull request closed without merging**
